using System;
using IntroduzioneAspNet;

ClasseParziale cp = new ClasseParziale();

cp.metodoUno();
cp.metodoDue();

//ANCHE SE I METODI SONO DEFINITI IN DUE CLASSI DIVERSE CON LO STESSO NOME,
//ESSENDO PARZIALI E CON LO STESSO NAMESPACE POSSONO COLLABORARE

/* QUESTE CLASSI SONO COMODE PERCHÈ ALCUNI TOOLS HANNO DELLE CLASSI IN
 * CUI NON POTREI AGGIUNGERE DEI METODI PERSONALI ALTRIMENTI IL FILE ORIGINALE VERREBBE
 * SOVRASCRITTO. CON LE CLASSI PARZIALI POSSO IMPLEMENTARE
 * I MIEI METODI ATTRAVERSO UN ALTRO FILE SENZA ANDARE A INTACCARE IL FILE DEL TOOL*/

